sudo: true
dist: trusty

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

node_js:
  - "7"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - ./bin/composer install --no-interaction --no-progress --no-suggest
    - ./vendor/bin/phake dotenv:create CHOWN_USER=$USER CHGRP_GROUP=$USER DB_NAME=app DB_ADMIN_USER=root DB_USER=root
    - if [ -d "config/CsvMigrations" ] || [ -d "config/Modules" ] ; then ./bin/cake validate ; fi
    - ./vendor/bin/phake app:install

before_script:
    - yarn install
    - ./bin/phpserv >/dev/null 2>&1 &
    - sleep 5

script:
  - yarn test
  - ./vendor/bin/phpunit --group example
  - ./vendor/bin/phpunit --exclude-group example
  - ./vendor/bin/phpcs
